# Generated by Django 5.0.6 on 2024-07-12 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_alter_hydjobs_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hydjobs',
            name='phonenumber',
            field=models.CharField(max_length=10),
        ),
    ]
